### ISSUE TITLE
update media section on homepage

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub-web#1]
can we update the media section to have a selection of the most high-profile titles/links of articles and then the logos of the news organizations? I like the layout on the main page of https://covidtracking.com/:
![image](https://user-images.githubusercontent.com/1280767/83953544-0b8d3200-a80f-11ea-8483-4cd159395f03.png)

Here are some LaTeX formatted entries of URLs, dates, sources. Let's just use the top 6 of this list on the index page:

- \href{https://www.economist.com/graphic-detail/2020/05/23/early-projections-of-covid-19-in-america-underestimated-its-severity}{``Early projections of covid-19 in America underestimated its severity''}. {\em The Economist}. 23 May 2020.
- \href{https://www.pbs.org/newshour/show/what-computer-based-models-can-tell-us-about-coronavirus-and-what-they-cant}{``What computer-based models can tell us about coronavirus-and what they can't''}. {\em PBS NewsHour}. 20 May 2020.
- \href{https://www.npr.org/sections/health-shots/2020/05/13/855038708/combining-different-models-new-coronavirus-projection-shows-110-000-deaths-by-ju}{``How To Make Sense of All The COVID-19 Projections? A New Model Combines Them''}. {\em NPR Morning Edition}. 13 May 2020.
 - https://www.wsj.com/articles/scientists-crunch-data-to-predict-how-many-people-will-get-coronavirus-11584479851
 - https://www.washingtonpost.com/health/coronavirus-hot-spots-erupt-across-the-country-experts-warn-of-possible-outbreaks-in-south/2020/05/20/49bc6d10-9ab4-11ea-a282-386f56d579e6_story.html
- \href{https://projects.fivethirtyeight.com/covid-forecasts/}{``Where The Latest COVID-19 Models Think We're Headed ? And Why They Disagree''}. {\em FiveThirtyEight}. 1 May 2020.
- \href{https://www.nytimes.com/interactive/2020/04/22/upshot/coronavirus-models.html}{``What 5 Coronavirus Models Say the Next Month Will Look Like''}. {\em NY Times}. 22 April 2020.
- \href{https://www.deccanherald.com/international/world-news-politics/us-milestone-of-100000-coronavirus-deaths-likely-by-june-833657.html}{``US milestone of 100,000 coronavirus deaths likely by June''}. {\em Agence France Press}. 5 May 2020.
- \href{https://www.bostonglobe.com/2020/05/07/metro/umass-professor-develops-ensemble-forecast-coronavirus-pandemic-projects-103000-deaths-nationwide-by-end-may/}{``UMass professor develops ensemble forecast for coronavirus pandemic; projects 103,000 deaths nationwide by end of May''}. {\em Boston Globe}. 7 May 2020.
 - https://www.wcvb.com/article/umass-model-projects-833-more-covid-19-deaths-in-state-by-4th-of-july/32819172#
 - https://www.politico.com/newsletters/politico-nightly-coronavirus-special-edition/2020/06/10/dont-call-it-a-second-wave-489488

**Comment by nickreich** [comment]
Please update the homepage but also include a complete list of all media hits in `doc/media/index.md`

**Comment by nickreich** [comment]
@hannanabdul55 I added a few additional links above. can we include the top 7 on the index page? 
 - economist
 - nytimes
 - washington post
 - wall st journal
 - NPR
 - PBS
 - FiveThirtyEight

**Comment by hannanabdul55** [comment]
@nickreich is there anything else to be done for this? Or can I close this?

**Comment by mzorn-58** [comment]
@nickreich Is this complete?
