### ISSUE TITLE
add netlify acknowledgment

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub-web#109]
Similar to what was added on the visualization site [here](https://github.com/reichlab/Covid-19-Hub-Vizualization/pull/105) 

That added the acknowledgement on the viz part of the site, but not on the main site. I think we should add it to the footer here too.

**Comment by bsweger** [comment]
Quick update on this: had some ruby troubles on the new machine, so I'll take a deeper look early next week.
