### ISSUE TITLE
delete community.md

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub-web#14]
I'm confused about how/where the community.md file lives, but I think we can delete the `~/community.md` file, right?

**Comment by hannanabdul55** [comment]
The `community.md` file is used to render that page. Though the content of `community.md` is not used anymore ("`Replicating a recent successful...`").

**Comment by nickreich** [comment]
ok. I think we can delete that text then.

**Comment by hannanabdul55** [comment]
Done. ref commit: https://github.com/reichlab/covid19-forecast-hub-web/commit/ccc418bda0ff2ccebddb05637d78abdfff0ded02
