### ISSUE TITLE
update team page content

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub-web#3]
add list (ideally with photos, similar to reichlab.io people page?) of all contributors to the project. As a starting point, we could use the list [here](https://github.com/reichlab/covid19-forecast-hub#the-covid-forecast-hub-team) although it is out of date.

**Comment by nickreich** [comment]
I've moved the location of the team page. Please edit the files in `doc/team`.

**Comment by mzorn-58** [comment]
@nickreich Can this be closed?

**Comment by nickreich** [comment]
At the very least the list of contributors needs to be updated. so no, not complete. not hard to close out either.

**Comment by nickreich** [comment]
I guess we don't need to add photos, though. that would be nice, but seems like it would require quite the re-design.
