### ISSUE TITLE
automate site deployment

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub-web#36]
Some of the web contributors are able to push data to the repo but aren't able to run the deployment script locally. could we set up the deployment script as a GitHub Action?

**Comment by hannanabdul55** [comment]
This is already done --> https://github.com/reichlab/covid19-forecast-hub-web/actions?query=workflow%3ADeploy 
I just added an enhancement to specify the `skip_gen` parameter to in the manual trigger input field.
