### ISSUE TITLE
Interview on vaccines for the media section

### ISSUE THREAD

**Issue by micokoch** [reichlab/covid19-forecast-hub-web#64]
The local Amherst Community Television station (Amherst Media) contacted the Reich Lab to interview someone on vaccines, and I (Alvaro J. Castro Rivadeneira) was asked to be that someone.
The show aired on Friday, December 11th, at 6 PM on Channel 12.
There is a permanent link posted on their YouTube channel here: https://youtu.be/vAA7Vjow4xo

**Comment by hannanabdul55** [comment]
Hi @micokoch, could you give a sentence like the link names over here: https://covid19forecasthub.org/doc/media/ ?

**Comment by micokoch** [comment]
Hi @hannanabdul55 , here are two options for the title:
1. Amherst Weekly Report: Season 1 Finale
2. Covid-19 Vaccine

Here is the second line:
Amherst Weekly Report | December 11, 2020

Do you need anything else?
