### ISSUE TITLE
add stat counter links to template

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub-web#7]
I have a preferred tracking site to use.

**Comment by hannanabdul55** [comment]
Should we use the same configuration for the StatCounter as the visualization one?

**Comment by hannanabdul55** [comment]
Currently added the configuration used in the viz page itself in https://github.com/reichlab/covid19-forecast-hub-web/commit/44c6eb360c505ee03f7a2533b200fd27f4350daf

**Comment by nickreich** [comment]
yes, fine to use the same configuration

**Comment by hannanabdul55** [comment]
Just checked the portal and cross-verified that this page is working. For example : 
![Screen Shot 2020-06-12 at 3 11 02 PM](https://user-images.githubusercontent.com/3615269/84538095-07ee2500-acbf-11ea-9f39-429d698372e5.png)
