### ISSUE TITLE
Remove submit button on single page

### ISSUE THREAD

**Issue by mzorn-58** [reichlab/covid19-forecast-hub-web#77]
Is it possible to remove the submit button and have the data automatically update when state and date are selected without clicking on submit?

https://covid19forecasthub.org/reports/single_page.html

**Comment by hannanabdul55** [comment]
Done in https://github.com/reichlab/covid19-forecast-hub-web/commit/bf5b196d80b4ee3e6811696f0e7c4c72697be408 . Although I have not removed the submit button for the case when the auto-submit does not work (which happens at times). Let me know if I should remove it anyways.
