### ISSUE TITLE
update visualization hosting location

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub-web#9]
- [x] create subdomain viz.covid19-forecast-hub.org
 - [x] host interactive visualization at this subdomain 
 - [x] forward current url (https://reichlab.io/covid19-forecast-hub/) to this subdomain

**Comment by hannanabdul55** [comment]
http://viz.covid19forecasthub.org/ opens up the visualization.

**Comment by hannanabdul55** [comment]
@nickreich  about task number 3, when do you think we should do that? I am not sure about this. Should we currently just keep it such that people navigating to the viz from the static site would go to the viz.covid19forecasthub.org page?

**Comment by hannanabdul55** [comment]
The last task is done and I verified it. if it does not work. Please restart your browser and it should work 👍
